### ISSUE TITLE
💖 Molecule-digitalocean is looking for maintainers

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/molecule-digitalocean#3]
The current status of this driver is unmaintained and I am looking forward to handle its maintenance to someone that wants to assure molecule can use this driver.

Unless we find a maintainer this driver will be removed from molecule all-in-one container.

I will support with CI/CD guidance and help.

**Comment by ssbarnea** [comment]
@danihodovic Are you interested to takeover? If you do I can provide support for you for the molecule side. Mainly it should not be hard to copy changes already made to the other drivers.

**Comment by danihodovic** [comment]
I don't think I have time to keep this up to date with other drivers. I can however make sure it works since I'm using DigitalOcean to test my own Ansible roles.

If it were up to me I'd like to keep the code as lean as possible as that makes the testing surface smaller.

**Comment by ssbarnea** [comment]
When I meant keep-up was related to look at similar fixes. Recent changes made for 3.x required almost identical changes to most drivers. I was not able to also do this one.

I do expect very little maintenance, for one driver. Still if you have >10, even little can become too much.

**Comment by danihodovic** [comment]
Sounds good Sorin :+1:

**Comment by gizero** [comment]
Hi! It looks like this repo still needs some maintenance as of now. I've recently used the driver which required me to make some changes to work. I'm willing to step up and help contributing those changes if it makes sense. I've started with a trivial documentation change in #10 but the CI loop seems broken for reasons unrelated to proposed change. @ssbarnea still available for support?

**Comment by danihodovic** [comment]
I've moved on from this to the AWS module because I consistently run into DigitalOcean limits.

**Comment by ssbarnea** [comment]
As of today I am forced to remove molecule-digitalocean driver from molecule as this project is not actively maintained and I faced a long issue of problems trying to fix it.

If anyone is willing to takeover, I will be happy to bring it back.  I recommend using matrix channel.

**Comment by mamercad** [comment]
@ssbarnea I'll take this over (I work for DigitalOcean and currently maintain [the collection](https://github.com/ansible-collections/community.digitalocean)).

**Comment by ssbarnea** [comment]
Super! Keep in mind to join devtools irc/matrix channel amd feel free to ask me about anything you need. As a genera hint, you can always look at what happens with other plugins, like molecule-podman. I will send you an invite later today.

**Comment by ssbarnea** [comment]
As of today I am archiving this project. If anyone wants to revive the plugin and maintain it, please make a PR to add it to https://github.com/ansible-community/molecule-plugins
