### ISSUE TITLE
Driver is not loaded by molecule

### ISSUE THREAD

**Issue by danihodovic** [pycontribs/molecule-digitalocean#5]
```sh
pip install molecule-digitalocean

$ molecule init role -d digitalocean
Usage: molecule init role [OPTIONS] ROLE_NAME
Try 'molecule init role --help' for help.

Error: Invalid value for '--driver-name' / '-d': invalid choice: digitalocean. (choose from delegated, docker, ec2, podman)

```

**Comment by aruntomar** [comment]
@danihodovic It seems that molecule-digitalocean module in pip is yet to be updated. my workaround this was to install the module directly from the repo. 

`pip3 install git+https://github.com/ansible-community/molecule-digitalocean.git`

verify that digitalocean driver is installed & registered with molecule by running the following command

`molecule drivers`
