### ISSUE TITLE
Installation instructions missing/outdated

### ISSUE THREAD

**Issue by cfra** [pycontribs/molecule-digitalocean#7]
Looking into how to install molecule-digitalocean, I ended up looking through `driver.py` since I couldn't find any other documentation.

[There](https://github.com/ansible-community/molecule-digitalocean/blob/04ac113d7f62092f131e92000960014d0cda50c7/molecule_digitalocean/driver.py#L47) it says:

```
$ pip install 'molecule[digitalocean]'
```

However, this doesn't seem to work anymore:

```
WARNING: molecule 3.1.0 does not provide the extra 'digitalocean'
```

The instructions should probably be updated.

**Comment by aruntomar** [comment]
@cfra I mentioned the workaround in another issue mentioned below. 

https://github.com/ansible-community/molecule-digitalocean/issues/5#issuecomment-741888756

**Comment by cfra** [comment]
Thank you for providing the info for the workaround. :+1: 

I still would be curious how this is supposed to work without the workaround.

Once I know, I would also be willing to cook up a patch.
